MAP = "map"
MAP_FIG = 'map-fig'
MAP_LAYER = 'map-layer'
TRANS_MAP_LAYER = 'transect-map-layer'
BATH_PLOT ='bath-plot'
SSP_PLOT = 'soundSpeedProfilePlot'
LAT_INPUT = 'latitude-input'
LON_INPUT = 'longitude-input'
GET_DATA_BUTTON='get-data-button'
BB_MIN = 'bounding-box-minutes'
BATH_SOURCE_DROPDOWN = 'bath-source-dropdown'
TAB_SPINNER='tab-loading-spinner'
TAB_SPINNER_SECONDARY='secondary-tab-loading-spinner'

BATH_ERROR = 'bath-error'
ALERT = 'alert-div'

SSP_MONTH_DROPDOWN ='SSP-month-dropdown'
WOA_DATA_MARKER = 'WOA-data-marker'
SSP_EXCLUDE_DROPDOWN = 'ssp-include'
OPTION_DIV = 'options-div'
FIGURE_DIV = 'figure-div'
TAB_CONTENT_DIV = 'tab-content-div'
TABS ='tabs'

TRANSECT_DROPDOWN='transect-dropdown'
TRANSECT_COLLAPSE='transect-collapse'
TRANSECT_COLLAPSE_BUTTON='transect-collapse-button'

LAT_INPUT_START = 'lat-input-start'
LAT_INPUT_END = 'lat-input-end'
LON_INPUT_START = 'lon-input-start'
LON_INPUT_END = 'lon-input-end'
RADIAL_STEP_INPUT = 'radial-step-input'
TRANS_INPUTS_DIV = 'transect-inputs-div'
AZ_INPUT = 'single-azimuth-input'
PLOT_TRANSECTS_BUTTON_S = 'plot-transects-single'
PLOT_TRANSECTS_BUTTON_S_AZ = 'plot-transects-single-az'
PLOT_TRANSECTS_BUTTON_M = 'plot-transects-multiple'
TRANSECT_PLOT = 'transect-figure-plot'
PRIMARY_FIGURE_COLUMN = 'primary-figure-column'
